-- ==============================================================================
-- ZEGAN HOMESTAY & CAFE - SUPABASE DATABASE SCHEMA
-- Jalankan query SQL ini di Supabase SQL Editor (Dashboard > SQL Editor > New Query)
-- ==============================================================================

-- 1. Tabel Tamu (Guests)
CREATE TABLE IF NOT EXISTS public.guests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  phone TEXT,
  email TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Tabel Tipe Kamar (Room Types)
CREATE TABLE IF NOT EXISTS public.room_types (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  base_price NUMERIC DEFAULT 0,
  weekend_price NUMERIC DEFAULT 0,
  capacity INTEGER DEFAULT 2,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Tabel Kamar Fisik (Rooms)
CREATE TABLE IF NOT EXISTS public.rooms (
  id TEXT PRIMARY KEY,
  room_number TEXT NOT NULL,
  status TEXT DEFAULT 'Available',
  room_type_id TEXT,
  occupied_until TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Tabel Pemesanan (Bookings)
CREATE TABLE IF NOT EXISTS public.bookings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  booking_code TEXT UNIQUE NOT NULL,
  guest_id BIGINT REFERENCES public.guests(id) ON DELETE SET NULL,
  room_id TEXT,
  room_name TEXT,
  room_number TEXT,
  check_in TEXT NOT NULL,
  check_out TEXT NOT NULL,
  check_in_time TEXT DEFAULT '14:00',
  check_out_time TEXT DEFAULT '12:00',
  adults INTEGER DEFAULT 1,
  extra_beds INTEGER DEFAULT 0,
  extra_bed_price NUMERIC DEFAULT 0,
  total_price NUMERIC DEFAULT 0,
  special_request TEXT,
  payment_status TEXT DEFAULT 'Pending',
  booking_status TEXT DEFAULT 'Pending',
  payment_proof_url TEXT,
  ktp_photo_url TEXT,
  admin_notification_sent BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Tabel Sinyal Layanan Kamar & Cafe (Service Signals)
CREATE TABLE IF NOT EXISTS public.service_signals (
  id TEXT PRIMARY KEY,
  room_number TEXT NOT NULL,
  type TEXT NOT NULL,
  details TEXT,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ==============================================================================
-- ROW LEVEL SECURITY (RLS) POLICIES
-- PENTING: Wajib diaktifkan agar tamu di halaman umum dapat membuat pesanan
-- ==============================================================================

ALTER TABLE public.guests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_types ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_signals ENABLE ROW LEVEL SECURITY;

-- Guests: Izinkan anonim insert dan select
DROP POLICY IF EXISTS "Allow anon insert guests" ON public.guests;
CREATE POLICY "Allow anon insert guests" ON public.guests FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon select guests" ON public.guests;
CREATE POLICY "Allow anon select guests" ON public.guests FOR SELECT TO anon USING (true);

-- Bookings: Izinkan anonim insert, select, dan update (untuk upload bukti bayar)
DROP POLICY IF EXISTS "Allow anon insert bookings" ON public.bookings;
CREATE POLICY "Allow anon insert bookings" ON public.bookings FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon select bookings" ON public.bookings;
CREATE POLICY "Allow anon select bookings" ON public.bookings FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Allow anon update bookings" ON public.bookings;
CREATE POLICY "Allow anon update bookings" ON public.bookings FOR UPDATE TO anon USING (true);

-- Rooms & Room Types: Izinkan anonim membaca status kamar
DROP POLICY IF EXISTS "Allow anon select rooms" ON public.rooms;
CREATE POLICY "Allow anon select rooms" ON public.rooms FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Allow anon update rooms" ON public.rooms;
CREATE POLICY "Allow anon update rooms" ON public.rooms FOR UPDATE TO anon USING (true);

DROP POLICY IF EXISTS "Allow anon select room_types" ON public.room_types;
CREATE POLICY "Allow anon select room_types" ON public.room_types FOR SELECT TO anon USING (true);

-- Service Signals: Izinkan anonim mengirim dan membaca sinyal layanan
DROP POLICY IF EXISTS "Allow anon insert signals" ON public.service_signals;
CREATE POLICY "Allow anon insert signals" ON public.service_signals FOR INSERT TO anon WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon select signals" ON public.service_signals;
CREATE POLICY "Allow anon select signals" ON public.service_signals FOR SELECT TO anon USING (true);

DROP POLICY IF EXISTS "Allow anon update signals" ON public.service_signals;
CREATE POLICY "Allow anon update signals" ON public.service_signals FOR UPDATE TO anon USING (true);
